### ISSUE TITLE
Express Error

### ISSUE THREAD

**Issue by mdestafadilah** [cluemediator/login-app-reactjs#2]
I don't know why, while i'm testing your code, show the error ...

```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.join (path.js:372:7)
    at noopServiceWorkerMiddleware (D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\express\lib\router\index.js:317:13)
    at D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\express\lib\router\index.js:335:12)
    at next (D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\express\lib\router\index.js:317:13)
    at D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\express\lib\router\index.js:335:12)
    at next (D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (D:\REACT-DEV\cluemediator\login-app-reactjs\node_modules\express\lib\router\layer.js:95:5)
```

**Comment by mdestafadilah** [comment]
I think this is not your code, i follow this step.
https://stackoverflow.com/a/60251427
